# black list wip branches, however if pull requests are created for one then
# travis should build it
branches:
  except:
    - /^(wip|WIP)(-|_).*$/
notifications:
  irc:
    channels:
      - "irc.freenode.org#ccdevs"
    on_success: change
    on_failure: always
  email:
    recipients:
      - stephen.bannasch@gmail.com
      - sfentress@concord.org
      - rpk@pobox.com
      - janikpiotrek@gmail.com
      - scytacki@concord.org
    on_success: change
    on_failure: always
install: sudo apt-get install libicu-dev
language: ruby
rvm:
  - "2.0.0"
before_script:
  - cp config/config.sample.yml config/config.yml
  - travis_retry bundle install --binstubs
  - travis_retry npm install
  - make prepare-submodules
  # see: http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "make test"
env:
  global:
  - secure: "0vTh/6CdVgi1g9sHSCtiJuURDPNTgiX5eAu98W6UZhACVC3mLKG+DeBLY0U8PPlv9oK8pJggAwRQiUWdmc214tDk7ZkrHXx02S8EQgDL1Xy57wLhismlVJOFapMA1wkI/pCHADtc1ycYo6lYGhEDzGswjktxNImk2d9APYSrA4A="
  - secure: "A430lxRQcBORvdmn7a5EHW6ffPt+iO+KC5ZqvR/sCuh/SRJDrPvGgY5+D4T6xAAybwNLDddUdbxZ3ACUT7oUVFbRNEJzfLSo6ugkMeK+BnABckG4Bh9BEAI4xhqiune09qBDoxwpAKQBCXGKS5q06snabbkfLjx2H+yPqGHCsSE="
after_success: "script/s3-deploy.sh"
