# whitelist
branches:
  only:
    - master
notifications:
  irc: "irc.freenode.org#ccdevs"
  email:
    recipients:
      - stephen.bannasch@gmail.com
      - sfentress@concord.org
      - rpk@pobox.com
      - janikpiotrek@gmail.com
language: node_js
node_js:
  - 0.10
before_script:
  - cp config/config.sample.yml config/config.yml
  - bundle install --binstubs
  - make clean; make
script: "make test"
