# black list wip branches, however if pull requests are created for one then
# travis should build it
branches:
  except:
    - /^(wip|WIP)(-|_).*$/
notifications:
  irc:
    channels:
      - "irc.freenode.org#ccdevs"
    on_success: change
    on_failure: always
  email:
    recipients:
      - stephen.bannasch@gmail.com
      - sfentress@concord.org
      - rpk@pobox.com
      - janikpiotrek@gmail.com
      - scytacki@concord.org
    on_success: change
    on_failure: always
install: sudo apt-get install libicu-dev
language: ruby
rvm:
  - "2.0.0"
before_script:
  - cp config/config.sample.yml config/config.yml
  - travis_retry bundle install --binstubs
  - make clean
  - make
  # see: http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "make test"
