---
:environment: development
:server:
  development:
    :hostname: visual.concord.org
  production:
    :hostname: visual.concord.org
:jsconfig:
  :sharing: true
  :logging: false
  :tracing: false
  :home: http://visual.concord.org
  :homeInteractivePath: /interactive.html
  :homeEmbeddablePath: /embeddable.html
  :utmCampaign:
  :fontface: Lato
:google_analytics:
  :account_id:
# password and alias for Java siging certificate.
:java:
  :password: cc1234
  :alias: concord
  :keystore_path: config/concord-keystore.jks
# deploy configuration for working with Amazon Web Services
:deploy:
  :targets:
  - :name: lab
    :url: lab.concord.org
    :branch: master
  - :name: lab-staging
    :url: lab-staging.concord.org
    :branch: master
  - :name: lab-dev
    :url: lab.dev.concord.org
    :branch: master
  - :name: lab2-dev
    :url: lab2.dev.concord.org
    :branch: master
  - :name: lab3-dev
    :url: lab3.dev.concord.org
    :branch: master
  :group_name: lab.dev
  :zone_domain: concord.org.
  :zone_records_name: dev.concord.org
  :pem:
    :name: lab-dev
    :path: ~/.ec2
