# Edit this file to set hostnames for development and
# production environments and save as settings.yml.

test:
  :hostname: localhost:3000

development:
  :hostname: localhost:3000

production:
  :hostname: lab.concord.org